services:
  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg
    restart: unless-stopped
    ports:
    - 3000:3000
    command:
    - gotenberg
    - --chromium-disable-javascript=true
    - --chromium-allow-list=file:///tmp/.*
    labels:
    - traefik.enable=false
    networks:
    - shared
networks:
  shared:
    external: true
